misquedadas-v3-2016-11-29

diff --git a/npm_scripts/test b/npm_scripts/test
--- a/npm_scripts/test
+++ b/npm_scripts/test
@@ -19,10 +19,10 @@ Qid=$(curl http://localhost:8080/quedadas 2> /dev/null | node tests/losids.js); 
 if (node tests/estavacia.js $Q); then echo 'BBDD test error - No hay "quedadas"'; exit 1; else echo 'HAY "quedadas": '$Q; fi
 #
 echo ''
-echo 'TESTS: Peñas, test para ver si hay "peñas" en la BBDD'; echo -n '  -->  '
-P=$(curl http://localhost:8080/penias 2> /dev/null | node tests/losnombres.js);   #echo '$P= '$P
-# las penias no tienen id ---
-if (node tests/estavacia.js $P); then echo 'BBDD test error - No hay "peñas"'; exit 1; else echo 'HAY "peñas": '$P; fi
+echo 'TESTS: Grupos, test para ver si hay "grupos" en la BBDD'; echo -n '  -->  '
+P=$(curl http://localhost:8080/grupos 2> /dev/null | node tests/losnombres.js);   #echo '$P= '$P
+# los grupos no tienen id ---
+if (node tests/estavacia.js $P); then echo 'BBDD test error - No hay "grupos"'; exit 1; else echo 'HAY "grupos": '$P; fi
 #
 echo ''
 echo 'TESTS: Gente, test para ver si hay "gente" en la BBDD'; echo -n '  -->  '
@@ -53,13 +53,13 @@ done
 echo '';
 #
 echo ''
-echo 'TESTS: Peña-quedadas, test para ver si hay "peña" para todas las "quedadas" en la BBDD'; echo -n '  -->  '
+echo 'TESTS: Grupo-quedadas, test para ver si hay "grupo" para todas las "quedadas" en la BBDD'; echo -n '  -->  '
 for qno in $Qid ; do       #echo '$qno= '$qno', $Qid= '$Qid;
    qna=$(curl http://localhost:8080/quedada/$qno 2> /dev/null | node tests/elnombre.js);  #echo '$qna= '$qna
-   p=$(curl http://localhost:8080/quedada/$qno 2> /dev/null | node tests/lapenia.js);     #echo '$p= '$p
-   if (node tests/estavacia.js $p); then echo 'BBDD test error - No hay "peña" en la "quedada" '$qna;
-   elif ! (node tests/estaen.js $p $P); then echo 'BBDD test error - No existe la "peña": '$p' de la "quedada": '$qna;
-   else echo -n 'Existe la "peña" '$p' de la "quedada" '$qna'. '; fi ;
+   p=$(curl http://localhost:8080/quedada/$qno 2> /dev/null | node tests/elgrupo.js);     #echo '$p= '$p
+   if (node tests/estavacia.js $p); then echo 'BBDD test error - No hay "grupo" en la "quedada" '$qna;
+   elif ! (node tests/estaen.js $p $P); then echo 'BBDD test error - No existe el "grupo": '$p' de la "quedada": '$qna;
+   else echo -n 'Existe el "grupo" '$p' de la "quedada" '$qna'. '; fi ;
 done
 echo '';
 #
@@ -97,18 +97,18 @@ done
 echo '';
 #
 echo ''
-echo 'TESTS: Gente-peñas, test para ver si hay "gente" para todas las "peñas" en la BBDD'; echo -n '  -->  '
-node tests/gente-penias.js
+echo 'TESTS: Gente-grupos, test para ver si hay "gente" para todas los "grupos" en la BBDD'; echo -n '  -->  '
+node tests/gente-grupos.js
 echo '';
 #
 echo ''
-echo 'TESTS: Fecha-de-creación-peñas, test para ver si hay "fecha de creación" para todas las "peñas" en la BBDD'; echo -n '  -->  '
-node tests/fecha-creacion-penias.js
+echo 'TESTS: Fecha-de-creación-grupos, test para ver si hay "fecha_creacion" para todas los "grupos" en la BBDD'; echo -n '  -->  '
+node tests/fecha-creacion-grupos.js
 echo '';
 #
 echo ''
-echo 'TESTS: Escudo-peñas, test para ver si hay "Escudo" para todas las "peñas" en la BBDD'; echo -n '  -->  '
-node tests/escudo-penias.js
+echo 'TESTS: Escudo-grupos, test para ver si hay "Escudo" para todas los "grupos" en la BBDD'; echo -n '  -->  '
+node tests/escudo-grupos.js
 #
 echo ''
 echo 'TESTS: Alias-gente, test para ver si hay "alias" para toda la gente en la BBDD'; echo -n '  -->  '
